### ISSUE TITLE
Command Line execute NPM code?

### ISSUE THREAD

**Issue by gmyx** [crazy-max/nodejs-portable#53]
I am trying to get command line going, but getting this error. It seems while not in the portable shell, it does not know about the work folder. I am working on automation, so I need a way to kick off a 'npm test' command.

.\nodejs-portable.exe npm test
```
internal/modules/cjs/loader.js:976
  throw err;
  ^

Error: Cannot find module 'D:\Updates\PupeteerTest\CandP\npm'
	[90m    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:973:15)	[39m
	[90m    at Function.Module._load (internal/modules/cjs/loader.js:855:27)	[39m
	[90m    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)	[39m
	[90m    at internal/main/run_main_module.js:17:47	[39m {
  code: 	[32m'MODULE_NOT_FOUND'	[39m,
  requireStack: []
}
```

**Comment by gmyx** [comment]
Forgot to add. Running on Windows 10 and PowerShell 5.

**Comment by gmyx** [comment]
I have some working code that does this. Will create a branch to implement.

**Comment by Temtaime** [comment]
Same question here. How to run a command like it is run from shell?
echo "cmd" | nodejs-portable.exe is an ugly way
